### PR TITLE
Migrated CSV data to SQL

### PR DESCRIPTION
**Pull request by cyberqubit**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
We are integrating functionality to convert CSV data to SQL within the repository.

## What did you learn from the changes you have made?
Gained a better understanding of data conversion processes and improved skills in integrating different data formats within the codebase.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
I was considering using PostgreSQL.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Tracking changes, testing thoroughly, and integrating seamlessly proved challenging. I implemented a Version Control System (VCS) for meticulous tracking. This allowed me to easily backtrack and collaborate effectively.

## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by cyberqubit** [comment]
I experimented with using SQLite3 to store the data as an SQL database. Specifically, I used the CSV files from the folder data_1  @jsoych @shabiga @rehanschaudhry @NabZaf

**Comment by cyberqubit** [comment]
load_data_to_db.py migrates the CSV files to a database. I modified classifer_1 as classifier_4 to fetch the data from the created database. It worked locally for me. @jsoych @shabiga @rehanschaudhry @NabZaf

**Comment by jsoych** [comment]
Hi José, I've looked over your additions and it does in fact look like you've successfully saved data_1 within a database. I don't think we need to add classifier_4.py to our main branch, since neither the classifier or the data is different from the classifiers that have been trained so far. 

If you're looking to work on your sqlite3 skills, maybe storing all of the results from our models to a database would be a nice addition to our project? @cyberqubit

**Comment by cyberqubit** [comment]
Thank you for your email, John. I agree. I will also experiment with
PostgreSQL.

**Pull request closed without merging**
